# Generated by Django 5.2.1 on 2025-06-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeptName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'OrgDepartment',
            },
        ),
        migrations.CreateModel(
            name='OrgDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DesName', models.CharField(max_length=100)),
                ('DepId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.orgdepartment')),
            ],
        ),
    ]
