# Generated by Django 5.2.1 on 2025-06-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orgdesignation',
            table='OrgDesignation',
        ),
    ]
