# Generated by Django 5.2.1 on 2025-05-26 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('mob_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('Designation', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_of_joning', models.DateTimeField(blank=True, max_length=20, null=True)),
                ('Date_of_resign', models.DateTimeField(blank=True, max_length=20, null=True)),
                ('Org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.organisation')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
