# Generated by Django 5.2.4 on 2025-07-21 09:19

import django.db.models.deletion
import employee.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dept', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TMEmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=255)),
                ('EmployeeId', models.CharField(max_length=50, unique=True)),
                ('EmpMobNumber', models.CharField(max_length=20, unique=True)),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to=employee.models.profile_image_upload_path)),
                ('DateOfJoining', models.DateField()),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('Address', models.TextField()),
                ('WorkLocation', models.CharField(max_length=255)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_created', to=settings.AUTH_USER_MODEL)),
                ('DepartmentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dept.orgdepartment')),
                ('DesignationId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dept.orgdesignation')),
                ('UpdatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TMEmployeeDetail',
            },
        ),
    ]
