# Generated by Django 5.2.4 on 2025-08-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmemployeedetail',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tmemployeedetail',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
