# Generated by Django 5.2.1 on 2025-05-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Date_of_joning',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Date_of_resign',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
