# Generated by Django 5.2.4 on 2025-09-30 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
        ('employee', '0002_tmemployeedetail_is_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmemployeedetail',
            name='EmployeeId',
        ),
        migrations.AlterField(
            model_name='tmemployeedetail',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmemployeedetail',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmemployeedetail',
            name='DateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmemployeedetail',
            name='DateOfJoining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmemployeedetail',
            name='DepartmentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dept.orgdepartment'),
        ),
        migrations.AlterField(
            model_name='tmemployeedetail',
            name='DesignationId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dept.orgdesignation'),
        ),
        migrations.AlterField(
            model_name='tmemployeedetail',
            name='EmpMobNumber',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tmemployeedetail',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tmemployeedetail',
            name='Status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tmemployeedetail',
            name='UpdatedOn',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tmemployeedetail',
            name='WorkLocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
