# Generated by Django 5.2.1 on 2025-07-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_tmemployeedetail_empmobnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmemployeedetail',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tmemployeedetail',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
