# Generated by Django 5.2.1 on 2025-06-04 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeechat',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_message', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employeechat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to='employee.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='employeechat',
            unique_together={('sender', 'receiver')},
        ),
    ]
