# Generated by Django 5.2.1 on 2025-06-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('password', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Superadmin',
            },
        ),
    ]
