# Generated by Django 5.2.1 on 2025-06-12 09:23

import django.db.models.deletion
import org.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TMOrganisationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrgName', models.CharField(max_length=100)),
                ('OrgCode', models.CharField(max_length=100)),
                ('OrgMobNum', models.CharField(max_length=20, unique=True)),
                ('Address', models.TextField()),
                ('ContPer', models.CharField(max_length=100)),
                ('ContPerEmail', models.EmailField(max_length=254)),
                ('ContPerNum', models.CharField(max_length=20, unique=True)),
                ('LogoImg', models.ImageField(blank=True, null=True, upload_to=org.models.logo_upload_path)),
                ('BusinessType', models.CharField(max_length=100)),
                ('RegistrationNumber', models.CharField(max_length=100, unique=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('CreatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_created', to=settings.AUTH_USER_MODEL)),
                ('UpdatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TMOrganisationDetail',
            },
        ),
    ]
