# Generated by Django 5.2.1 on 2025-06-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrgCode', models.CharField(blank=True, max_length=100, null=True)),
                ('OrgName', models.CharField(blank=True, max_length=150, null=True)),
                ('OrgEmail', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('OrgNumber', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'Organisation',
            },
        ),
    ]
