# Generated by Django 5.2.1 on 2025-06-04 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrgCode', models.CharField(blank=True, max_length=100, null=True)),
                ('OrgNumber', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user', models.OneToOneField(blank=True, limit_choices_to={'role': 'organisation'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Organisation',
            },
        ),
    ]
