# Generated by Django 5.2.1 on 2025-07-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_alter_tmorganisationdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmorganisationdetail',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
