# Generated by Django 5.2.4 on 2025-08-21 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0003_alter_employeegroup_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeegroup',
            name='members',
            field=models.ManyToManyField(related_name='empgroup', to=settings.AUTH_USER_MODEL),
        ),
    ]
