# Generated by Django 5.2.4 on 2025-08-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_tmemployeedetail_is_online_and_more'),
        ('groupchat', '0004_alter_employeegroup_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeegroup',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='employee.tmemployeedetail'),
        ),
    ]
