# Generated by Django 5.2.4 on 2025-08-21 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_tmemployeedetail_is_online_and_more'),
        ('groupchat', '0005_alter_employeegroup_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeegroup',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='employeegroup',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.AlterField(
            model_name='employeegroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_created_on', to='employee.tmemployeedetail'),
        ),
        migrations.AlterField(
            model_name='employeegroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_created_by', to='employee.tmemployeedetail'),
        ),
    ]
