# Generated by Django 5.2.4 on 2025-08-21 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_tmemployeedetail_is_online_and_more'),
        ('groupchat', '0006_rename_created_at_employeegroup_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeegroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_created_on', to='employee.tmemployeedetail'),
        ),
        migrations.AlterField(
            model_name='employeegroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_created_by', to='employee.tmemployeedetail'),
        ),
    ]
