# Generated by Django 5.2.4 on 2025-08-27 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_tmemployeedetail_is_online_and_more'),
        ('groupchat', '0008_remove_employeegroup_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeegroupmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.tmemployeedetail'),
        ),
    ]
