# Generated by Django 5.2.4 on 2025-08-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupchat', '0009_alter_employeegroupmember_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeegroup',
            table='EmployeeGroup',
        ),
        migrations.AlterModelTable(
            name='employeegroupmember',
            table='EmployeeGroupMember',
        ),
    ]
