# Generated by Django 5.2.4 on 2025-08-28 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_tmemployeedetail_is_online_and_more'),
        ('groupchat', '0010_alter_employeegroup_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeegroupchat',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.tmemployeedetail'),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.tmemployeedetail'),
        ),
    ]
