# Generated by Django 5.2.1 on 2025-06-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organisation',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='employee',
            new_name='user',
        ),
    ]
