# Generated by Django 5.2.4 on 2025-08-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmrole',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Superadmin'), ('2', 'Admin'), ('3', 'User')], primary_key=True, serialize=False),
        ),
    ]
