# Generated by Django 5.2.1 on 2025-06-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_rename_organisation_user_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='emp_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='org_id',
        ),
    ]
