# Generated by Django 5.2.1 on 2025-07-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_rename_user_user_emp_id_rename_admin_user_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tmrole',
            name='RoleName',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
